apiVersion: apps/v1
kind: Deployment
metadata:
 name: golang-deployment
spec:
  selector:
    matchLabels:
      app: golang-pod
  replicas: 1
  template:
    metadata:
      labels:
        app: golang-pod
    spec:
      containers:
        - name: golang-container
          image: robsoni/utilizandok8s_img
          ports:
            - containerPort: 8000