apiVersion: apps/v1
kind: Deployment
metadata:
 name: pod-nginx
spec:
  selector:
    matchLabels:
      app: pod-nginx
  replicas: 3
  template:
    metadata:
      labels:
        app: pod-nginx
    spec:
      containers:
        - name: container-nginx
          image: nginx:1.17-alpine
          ports:
            - containerPort: 80
          
          volumeMounts:
          - mountPath: /usr/share/nginx/html
            name: volume-nginx
            readOnly: true

      volumes:
      - name: volume-nginx
        configMap:
          name: nginx-configmap
          items:
            - key: index
              path: index.html